[build]
builder = "nixpacks"

[deploy]
startCommand = "cp /app/nginx.conf /etc/nginx/conf.d/default.conf && envsubst '$PORT' < /app/nginx.conf > /etc/nginx/conf.d/default.conf && cp -r /app/dist/* /usr/share/nginx/html/ && nginx -g 'daemon off;'"
healthcheckPath = "/"
healthcheckTimeout = 30
